name: MineRegion
version: '${project.version}'
main: net.danh.mineregion.MineRegion
description: Plugin will help you mine block in custom region and execute command when block broken by player
api-version: '1.13'
depend:
  - WorldGuard
  - PlaceholderAPI
softdepend:
  - MiningContest
commands:
  mr:
    description: MineRegion Command
    aliases:
      - mineregion
      - mregion
